- name: Run flush test
  include_tasks: flush-test.yml
  vars:
    port: "{{ conga_config.quickstart.port }}"
    flush_target: "{{ conga_config.replication.publish.flushTarget }}"
    type: "publish"
  when: conga_config.replication.publish.flushTarget