---
- name: "Set flush agent name."
  set_fact:
    __flush_agent_name: "{{ flush_target.name | regex_replace('\\.', '_') }}"

- name: "Running connection test for '{{ __flush_agent_name }}', type: '{{ type }}'."
  uri:
    url: "http://localhost:{{ port }}/etc/replication/agents.{{ type }}/flush_{{ __flush_agent_name }}.test.html"
    user: "{{ conga_aemst_user }}"
    password: "{{ conga_aemst_password }}"
    force_basic_auth: yes
    return_content: yes
    timeout: "{{ conga_aemst_flush_test_timeout }}"
  register: flush_test_result
  failed_when: conga_aemst_flush_test_pattern not in flush_test_result.content
