- name: "Running connection test for '{{ flush_target.name | regex_replace('\\.', '_') }}', type: '{{ type }}'"
  uri:
    url: "http://localhost:{{ port }}/etc/replication/agents.{{ type }}/flush_{{ flush_target.name | regex_replace('\\.', '_') }}.test.html"
    user: "{{ conga_aemst_user }}"
    password: "{{ conga_aemst_password }}"
    force_basic_auth: yes
    return_content: yes
  register: flush_test_result
  failed_when: conga_aemst_flush_test_pattern not in flush_test_result.content
