- name: "Set flush agent name."
  set_fact:
    __flush_agent_name: "{{ flush_target.name | regex_replace('\\.', '_') }}"

- name: Debug output
  debug:
    msg:
      - __flush_agent_name
      - "{{ __flush_agent_name }}"

- name: "Running connection test for '{{ __flush_agent_name }}', type: '{{ type }}'."
  uri:
    url: "http://localhost:{{ port }}/etc/replication/agents.{{ type }}/flush_{{ __flush_agent_name }}.test.html"
    user: "{{ conga_aemst_user }}"
    password: "{{ conga_aemst_password }}"
    force_basic_auth: yes
    return_content: yes
    timeout: "{{ conga_aemst_flush_test_timeout }}"
  register: flush_test_result
  failed_when: conga_aemst_flush_test_pattern not in flush_test_result.content

- name: Debug output
  debug:
    msg:
      - conga_aemst_flush_test_pattern
      - "{{ conga_aemst_flush_test_pattern }}"
      - flush_test_result
      - "{{ flush_test_result }}"

- name: Assert that flush test was successful.
  assert:
    that:
      - conga_aemst_flush_test_pattern in flush_test_result.content
    success_msg: "Connection test for '{{ __publish_agent_name }}' successful."
    fail_msg: "Connection test for '{{ __publish_agent_name }}' failed."

