---
- name: "Set publish agent name."
  set_fact:
    __publish_agent_name: "{{ publish_target.name | regex_replace('\\.', '_') }}"

- name: "Running connection test for '{{ __publish_agent_name }}'."
  uri:
    url: "http://localhost:{{ port }}/etc/replication/agents.author/publish_{{ __publish_agent_name }}.test.html"
    user: "{{ conga_aemst_user }}"
    password: "{{ conga_aemst_password }}"
    return_content: yes
    timeout: "{{ conga_aemst_publish_test_timeout }}"
  register: connection_test_result
  failed_when: conga_aemst_publish_test_pattern not in connection_test_result.content
