- name: "Running connection test for '{{ publish_target.name | regex_replace('\\.', '_') }}'"
  uri:
    url: "http://localhost:{{ port }}/etc/replication/agents.author/publish_{{ publish_target.name | regex_replace('\\.', '_') }}.test.html"
    user: "{{ conga_aemst_user }}"
    password: "{{ conga_aemst_password }}"
    return_content: yes
  register: connection_test_result
  failed_when: conga_aemst_publish_test_pattern not in connection_test_result.content
